esphome:
  name: fridge
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  <<: !include ./secrets.yaml

  fast_connect: true
  manual_ip:
    static_ip: 10.0.0.41
    gateway: 10.0.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

ota:

mqtt:
  broker: 10.0.0.254

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: "Sonoff Lamp"
    pin: GPIO12
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: true
