esphome:
  name: table
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  fast_connect: true
  power_save_mode: none
  manual_ip:
    static_ip: 10.0.0.42
    gateway: 10.0.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

ota:
  platform: esphome

mqtt:
  broker: 10.0.0.254

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: "Sonoff Lamp"
    pin: GPIO12
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: true
